<div class="carouselWrapper">

        <div id="homeCarousel" class="carousel slide" data-ride="carousel">                    
            <ol class="carousel-indicators">
                <li data-target="#homeCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#homeCarousel" data-slide-to="1"></li>
                <li data-target="#homeCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="<?php echo $this->getSkinUrl('images/sliderImage.jpg'); ?>" alt="First Slide Image">
                    <div class="carousel-caption">
                        First slide
                    </div>
                </div>
                <div class="item">
                    <img src="<?php echo $this->getSkinUrl('images/sliderImage.jpg'); ?>" alt="Second Slide Image">
                    <div class="carousel-caption">
                        Second Slide
                    </div>
                </div>
                <div class="item">
                    <img src="<?php echo $this->getSkinUrl('images/sliderImage.jpg'); ?>" alt="Third Slide Image">
                    <div class="carousel-caption">
                        Third Slide
                    </div>
                </div>
            </div>

            <a class="left carousel-control" href="#homeCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#homeCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

</div>